apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spiffe-demo-client
spec:
  className: zero-trust-workload-identity-manager-spire
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      app: spiffe-client-app
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: spiffe-demo
  jwtTtl: "5m"
  ttl: "1h"
