FROM python:3.11-slim

WORKDIR /app

COPY requirements-api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY api-server.py app.py

EXPOSE 8080

USER 1001

CMD ["python", "app.py"]
