apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app
spec:
  output:
    to:
      kind: ImageStreamTag
      name: demo-app:latest
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers: []
