apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: db-client-app
  namespace: spiffe-edb-demo
  labels:
    app: db-client-app
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: db-client-app:latest
  triggers: []
